# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBvfFoLtQI8gxedvrBM1Sz8Wj2eDjyMt
"""

!pip install transformers accelerate sentencepiece gradio --quiet

from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model="ibm-granite/granite-3.3-2b-instruct",
    max_new_tokens=200
)

def extract_drug_info(text):
    messages = [{"role": "user", "content": f"Extract drug name, dosage, frequency from: {text}"}]
    output = pipe(messages)
    return output[0]["generated_text"]

# Dummy datasets — editable
drug_interactions = {
    ("aspirin", "ibuprofen"): "High Risk: Both are NSAIDs — stomach bleeding possible.",
    ("paracetamol", "ibuprofen"): "Safe in normal doses."
}

age_dosage = {
    "paracetamol": {"child": "250 mg", "adult": "500 mg"},
    "ibuprofen": {"child": "100 mg", "adult": "400 mg"},
}

alternative_drugs = {
    "aspirin": ["paracetamol", "acetaminophen"],
    "ibuprofen": ["naproxen"],
}

def detect_interactions(drugs):
    warnings = []
    for i in range(len(drugs)):
        for j in range(i+1, len(drugs)):
            pair = (drugs[i], drugs[j])
            rev = (drugs[j], drugs[i])
            if pair in drug_interactions:
                warnings.append(drug_interactions[pair])
            elif rev in drug_interactions:
                warnings.append(drug_interactions[rev])
    return warnings

def recommend_dosage(drug, age):
    age_group = "child" if age < 18 else "adult"
    return age_dosage.get(drug, {}).get(age_group, "No dosage data")

def suggest_alternatives(drug):
    return alternative_drugs.get(drug, ["No alternatives found"])

def analyze(drug_string, age, medical_text):
    if not drug_string:
        return "Enter drug names!", "", "", ""

    # clean drug list
    drugs = [d.strip().lower() for d in drug_string.split(",")]

    extracted = extract_drug_info(medical_text) if medical_text else "No text provided"
    interactions = detect_interactions(drugs)
    dosage = {d: recommend_dosage(d, age) for d in drugs}
    alternatives = {d: suggest_alternatives(d) for d in drugs}

    return (
        extracted,
        "\n".join(interactions) if interactions else "No harmful interactions 👍",
        dosage,
        alternatives
    )

import gradio as gr

with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("<h1 style='text-align:center;'>💊 Drug Interaction & Dosage Analysis System</h1>")
    gr.Markdown("Enter patient details and drugs below.")

    with gr.Row():
        drug_input = gr.Textbox(label="Drugs (comma-separated)", placeholder="e.g., aspirin, ibuprofen")
        age_input = gr.Number(label="Patient Age", value=25)

    medical_input = gr.Textbox(
        label="Medical Prescription Text (Optional)",
        placeholder="e.g., Take 2 tablets of Paracetamol daily..."
    )

    analyze_btn = gr.Button("Analyze", variant="primary")

    extracted_output = gr.Textbox(label="📌 Extracted Drug Info (IBM Granite)")
    interaction_output = gr.Textbox(label="⚠ Interaction Warnings")
    dosage_output = gr.JSON(label="💉 Dosage Recommendations")
    alt_output = gr.JSON(label="🔄 Alternative Medication")

    analyze_btn.click(
        analyze,
        inputs=[drug_input, age_input, medical_input],
        outputs=[extracted_output, interaction_output, dosage_output, alt_output]
    )

demo.launch()